### ISSUE TITLE
Dependabot not checking icon pack's package.json for updates

### ISSUE THREAD

**Issue by stramel** [svg-icons/svg-icons#18]
I published the newest icons on the material packs and noticed that dependabot hadn't checked it. Looking at what it checked it appears to just be the automerge.yml and root package.json.

@jacobwgillespie Is this a limitation to dependabot?

**Comment by jacobwgillespie** [comment]
Icon updates! 🎉 

---

I believe this is an issue where Dependabot only checks for updates once per day, I think it last checked at 5am UK time ([logs](https://github.com/svg-icons/svg-icons/network/updates/32790087)) and your release was around 7am UK time. I manually triggered another check, so it should pick up the update shortly.

It does check more than the root `package.json`, you just have to click on the three dots to see what all it covers with that file (it reads the whole Yarn workspace from the root file):

On https://github.com/svg-icons/svg-icons/network/updates:

<img width="271" alt="Screenshot 2020-06-30 at 19 03 38" src="https://user-images.githubusercontent.com/130874/86161108-aaeacf80-bb04-11ea-82eb-1bf57ce52321.png">

**Comment by stramel** [comment]
Ah, okay. That's a bit misleading but sorry for the noise. Excited to see it run!
